[package]
name = "nftbk"
version = "0.1.0"
edition = "2021"
description = "CLI tool for backing up NFT metadata and content"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
clap = { version = "4.3", features = ["derive"] }
ethers = { version = "2.0", features = ["rustls"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
url = "2.4"
futures = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
