ethereum = "https://eth-mainnet.g.alchemy.com/v2/${ETH_RPC_API_KEY}"
tezos = "https://mainnet.smartpy.io"
zora = "https://rpc.zora.energy"
base = "https://mainnet.base.org"
arbitrum = "https://1rpc.io/arb"
shape = "https://mainnet.shape.network"
