arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${EVM_RPC_API_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${EVM_RPC_API_KEY}"
ethereum = "https://eth-mainnet.g.alchemy.com/v2/${EVM_RPC_API_KEY}"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${EVM_RPC_API_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${EVM_RPC_API_KEY}"
shape = "https://shape-mainnet.g.alchemy.com/v2/${EVM_RPC_API_KEY}"
tezos = "https://mainnet.smartpy.io"
zora = "https://zora-mainnet.g.alchemy.com/v2/${EVM_RPC_API_KEY}"
