# Example IPFS Provider Configuration
# This file configures IPFS pinning providers for the nftbk server

# Example 1: Standard IPFS Pinning Service with token from environment variable
[[ipfs_provider]]
type = "pinning-service"
base_url = "https://my-ipfs-service.example.com"
# bearer_token_env references an environment variable name
bearer_token_env = "IPFS_PINNING_SERVICE_TOKEN"

# Example 2: Pinata with token from environment variable (recommended)
[[ipfs_provider]]
type = "pinata"
base_url = "https://api.pinata.cloud"
bearer_token_env = "PINATA_TOKEN"

# Example 3: Another Pinata instance with a different token
#[[ipfs_provider]]
#type = "pinata"
#base_url = "https://api.pinata.cloud"
#bearer_token_env = "PINATA_BACKUP_TOKEN"

# Note: You can also embed tokens directly (not recommended for production):
# bearer_token = "your_actual_token_here"
# If both bearer_token and bearer_token_env are provided, bearer_token_env takes precedence
