# This compose file uses .env.postgres for Postgres credentials
version: '3.8'
services:
  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
 