version: "3.8"
services:

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nftbk-server:
    image: ghcr.io/0xmichalis/nftbk-server:latest
    pull_policy: always
    env_file:
      - .env
    expose:
      - "8080"
    volumes:
      - ./data:/app/data
    user: "65532:65532"
    command: [
      "/app/nftbk-server",
      "--listen-address", "0.0.0.0:8080",
      "--unsafe-skip-checksum-check", "true",
      "--base-dir", "/app/data",
      "--no-color", "true"
    ]
    restart: unless-stopped

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.template:/etc/caddy/Caddyfile.template
      - ./scripts/start_caddy.sh:/start_caddy.sh
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env.caddy
    entrypoint: ["/bin/sh", "/start_caddy.sh"]
    depends_on:
      - nftbk-server
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  pgdata:
